/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Apr  9 16:24:34 2024.
 */

#include <string.h>

#include "opel_omega_2001.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int opel_omega_2001_tcu_data1_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_tcu_data1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->torque_request1, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->torque_request2, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->output_shaft_speed, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->output_shaft_speed, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_tcu_data1_unpack(
    struct opel_omega_2001_tcu_data1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->torque_request1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->torque_request2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->output_shaft_speed = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->output_shaft_speed |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_tcu_data1_init(struct opel_omega_2001_tcu_data1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_tcu_data1_t));

    return 0;
}

uint8_t opel_omega_2001_tcu_data1_torque_request1_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data1_torque_request1_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data1_torque_request1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_tcu_data1_torque_request2_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data1_torque_request2_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data1_torque_request2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t opel_omega_2001_tcu_data1_output_shaft_speed_encode(double value)
{
    return (uint16_t)(value);
}

double opel_omega_2001_tcu_data1_output_shaft_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data1_output_shaft_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int opel_omega_2001_esp_data1_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_esp_data1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->abd_active, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->torque_request_fast, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->torque_request_slow, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_esp_data1_unpack(
    struct opel_omega_2001_esp_data1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abd_active = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->torque_request_fast = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->torque_request_slow = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_esp_data1_init(struct opel_omega_2001_esp_data1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_esp_data1_t));

    return 0;
}

uint8_t opel_omega_2001_esp_data1_abd_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data1_abd_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data1_abd_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_esp_data1_torque_request_fast_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data1_torque_request_fast_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data1_torque_request_fast_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_esp_data1_torque_request_slow_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data1_torque_request_slow_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data1_torque_request_slow_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int opel_omega_2001_sas_data_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_sas_data_t *src_p,
    size_t size)
{
    uint16_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    steering_angle = (uint16_t)src_p->steering_angle;
    dst_p[0] |= pack_left_shift_u16(steering_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(steering_angle, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->steering_speed, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_sas_data_unpack(
    struct opel_omega_2001_sas_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    steering_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    steering_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->steering_angle = (int16_t)steering_angle;
    dst_p->steering_speed = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_sas_data_init(struct opel_omega_2001_sas_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_sas_data_t));

    return 0;
}

int16_t opel_omega_2001_sas_data_steering_angle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double opel_omega_2001_sas_data_steering_angle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool opel_omega_2001_sas_data_steering_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_sas_data_steering_speed_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_sas_data_steering_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_sas_data_steering_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int opel_omega_2001_ecu_data1_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_ecu_data1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->torque_response, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->torque_lost, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->app, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->torque_request, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_ecu_data1_unpack(
    struct opel_omega_2001_ecu_data1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rpm |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->torque_response = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->torque_lost = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->app = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->torque_request = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_ecu_data1_init(struct opel_omega_2001_ecu_data1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_ecu_data1_t));

    return 0;
}

uint16_t opel_omega_2001_ecu_data1_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double opel_omega_2001_ecu_data1_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data1_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_ecu_data1_torque_response_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data1_torque_response_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data1_torque_response_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_ecu_data1_torque_lost_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data1_torque_lost_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data1_torque_lost_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t opel_omega_2001_ecu_data1_app_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data1_app_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data1_app_is_in_range(uint8_t value)
{
    return (value <= 102u);
}

uint8_t opel_omega_2001_ecu_data1_torque_request_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data1_torque_request_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data1_torque_request_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int opel_omega_2001_ecu_data2_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_ecu_data2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->tps, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_ecu_data2_unpack(
    struct opel_omega_2001_ecu_data2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->tps = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_ecu_data2_init(struct opel_omega_2001_ecu_data2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_ecu_data2_t));

    return 0;
}

uint8_t opel_omega_2001_ecu_data2_tps_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data2_tps_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data2_tps_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int opel_omega_2001_ecu_data3_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_ecu_data3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->cruise_active, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->kickdown_active, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_active, 2u, 0x04u);

    return (8);
}

int opel_omega_2001_ecu_data3_unpack(
    struct opel_omega_2001_ecu_data3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cruise_active = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->kickdown_active = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->brake_active = unpack_right_shift_u8(src_p[2], 2u, 0x04u);

    return (0);
}

int opel_omega_2001_ecu_data3_init(struct opel_omega_2001_ecu_data3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_ecu_data3_t));

    return 0;
}

uint8_t opel_omega_2001_ecu_data3_cruise_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data3_cruise_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data3_cruise_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_ecu_data3_kickdown_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data3_kickdown_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data3_kickdown_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_ecu_data3_brake_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_ecu_data3_brake_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_ecu_data3_brake_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int opel_omega_2001_tcu_data2_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_tcu_data2_t *src_p,
    size_t size)
{
    uint8_t tot;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tot = (uint8_t)src_p->tot;
    dst_p[3] |= pack_left_shift_u8(tot, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->input_shaft_speed, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->input_shaft_speed, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_tcu_data2_unpack(
    struct opel_omega_2001_tcu_data2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t tot;

    if (size < 8u) {
        return (-EINVAL);
    }

    tot = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->tot = (int8_t)tot;
    dst_p->input_shaft_speed = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->input_shaft_speed |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_tcu_data2_init(struct opel_omega_2001_tcu_data2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_tcu_data2_t));

    return 0;
}

int8_t opel_omega_2001_tcu_data2_tot_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double opel_omega_2001_tcu_data2_tot_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool opel_omega_2001_tcu_data2_tot_is_in_range(int8_t value)
{
    return (value >= 0);
}

uint16_t opel_omega_2001_tcu_data2_input_shaft_speed_encode(double value)
{
    return (uint16_t)(value);
}

double opel_omega_2001_tcu_data2_input_shaft_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data2_input_shaft_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int opel_omega_2001_abs_wheel_speed_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_abs_wheel_speed_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->front_left_wheel_error_flag, 7u, 0x80u);
    dst_p[0] |= pack_right_shift_u16(src_p->front_left_wheel_speed, 8u, 0x3fu);
    dst_p[1] |= pack_left_shift_u16(src_p->front_left_wheel_speed, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->front_right_wheel_error_flag, 7u, 0x80u);
    dst_p[2] |= pack_right_shift_u16(src_p->front_right_wheel_speed, 8u, 0x3fu);
    dst_p[3] |= pack_left_shift_u16(src_p->front_right_wheel_speed, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->rear_left_wheel_error_flag, 7u, 0x80u);
    dst_p[4] |= pack_right_shift_u16(src_p->rear_left_wheel_speed, 8u, 0x3fu);
    dst_p[5] |= pack_left_shift_u16(src_p->rear_left_wheel_speed, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->rear_right_wheel_error_flag, 7u, 0x80u);
    dst_p[6] |= pack_right_shift_u16(src_p->rear_right_wheel_speed, 8u, 0x3fu);
    dst_p[7] |= pack_left_shift_u16(src_p->rear_right_wheel_speed, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_abs_wheel_speed_unpack(
    struct opel_omega_2001_abs_wheel_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->front_left_wheel_error_flag = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->front_left_wheel_speed = unpack_left_shift_u16(src_p[0], 8u, 0x3fu);
    dst_p->front_left_wheel_speed |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->front_right_wheel_error_flag = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->front_right_wheel_speed = unpack_left_shift_u16(src_p[2], 8u, 0x3fu);
    dst_p->front_right_wheel_speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rear_left_wheel_error_flag = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->rear_left_wheel_speed = unpack_left_shift_u16(src_p[4], 8u, 0x3fu);
    dst_p->rear_left_wheel_speed |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rear_right_wheel_error_flag = unpack_right_shift_u8(src_p[6], 7u, 0x80u);
    dst_p->rear_right_wheel_speed = unpack_left_shift_u16(src_p[6], 8u, 0x3fu);
    dst_p->rear_right_wheel_speed |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int opel_omega_2001_abs_wheel_speed_init(struct opel_omega_2001_abs_wheel_speed_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_abs_wheel_speed_t));

    return 0;
}

uint8_t opel_omega_2001_abs_wheel_speed_front_left_wheel_error_flag_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_abs_wheel_speed_front_left_wheel_error_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_abs_wheel_speed_front_left_wheel_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t opel_omega_2001_abs_wheel_speed_front_left_wheel_speed_encode(double value)
{
    return (uint16_t)(value / 0.112);
}

double opel_omega_2001_abs_wheel_speed_front_left_wheel_speed_decode(uint16_t value)
{
    return ((double)value * 0.112);
}

bool opel_omega_2001_abs_wheel_speed_front_left_wheel_speed_is_in_range(uint16_t value)
{
    return (value <= 2277u);
}

uint8_t opel_omega_2001_abs_wheel_speed_front_right_wheel_error_flag_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_abs_wheel_speed_front_right_wheel_error_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_abs_wheel_speed_front_right_wheel_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t opel_omega_2001_abs_wheel_speed_front_right_wheel_speed_encode(double value)
{
    return (uint16_t)(value / 0.112);
}

double opel_omega_2001_abs_wheel_speed_front_right_wheel_speed_decode(uint16_t value)
{
    return ((double)value * 0.112);
}

bool opel_omega_2001_abs_wheel_speed_front_right_wheel_speed_is_in_range(uint16_t value)
{
    return (value <= 2277u);
}

uint8_t opel_omega_2001_abs_wheel_speed_rear_left_wheel_error_flag_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_abs_wheel_speed_rear_left_wheel_error_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_abs_wheel_speed_rear_left_wheel_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t opel_omega_2001_abs_wheel_speed_rear_left_wheel_speed_encode(double value)
{
    return (uint16_t)(value / 0.112);
}

double opel_omega_2001_abs_wheel_speed_rear_left_wheel_speed_decode(uint16_t value)
{
    return ((double)value * 0.112);
}

bool opel_omega_2001_abs_wheel_speed_rear_left_wheel_speed_is_in_range(uint16_t value)
{
    return (value <= 2277u);
}

uint8_t opel_omega_2001_abs_wheel_speed_rear_right_wheel_error_flag_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_abs_wheel_speed_rear_right_wheel_error_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_abs_wheel_speed_rear_right_wheel_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t opel_omega_2001_abs_wheel_speed_rear_right_wheel_speed_encode(double value)
{
    return (uint16_t)(value / 0.112);
}

double opel_omega_2001_abs_wheel_speed_rear_right_wheel_speed_decode(uint16_t value)
{
    return ((double)value * 0.112);
}

bool opel_omega_2001_abs_wheel_speed_rear_right_wheel_speed_is_in_range(uint16_t value)
{
    return (value <= 2277u);
}

int opel_omega_2001_esp_data2_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_esp_data2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->abs_active, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->esp_active, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->esp_off, 4u, 0x10u);

    return (8);
}

int opel_omega_2001_esp_data2_unpack(
    struct opel_omega_2001_esp_data2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abs_active = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->esp_active = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->esp_off = unpack_right_shift_u8(src_p[2], 4u, 0x10u);

    return (0);
}

int opel_omega_2001_esp_data2_init(struct opel_omega_2001_esp_data2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_esp_data2_t));

    return 0;
}

uint8_t opel_omega_2001_esp_data2_abs_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data2_abs_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data2_abs_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_esp_data2_esp_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data2_esp_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data2_esp_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_esp_data2_esp_off_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_esp_data2_esp_off_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_esp_data2_esp_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int opel_omega_2001_tcu_data3_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_tcu_data3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->current_gear, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->selector_position, 0u, 0x07u);
    dst_p[3] |= pack_left_shift_u8(src_p->sport_mode_active, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->winter_mode_active, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->auto_neutral_active, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->tcc_state, 4u, 0x30u);

    return (8);
}

int opel_omega_2001_tcu_data3_unpack(
    struct opel_omega_2001_tcu_data3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->current_gear = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->selector_position = unpack_right_shift_u8(src_p[2], 0u, 0x07u);
    dst_p->sport_mode_active = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->winter_mode_active = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->auto_neutral_active = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->tcc_state = unpack_right_shift_u8(src_p[4], 4u, 0x30u);

    return (0);
}

int opel_omega_2001_tcu_data3_init(struct opel_omega_2001_tcu_data3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_tcu_data3_t));

    return 0;
}

uint8_t opel_omega_2001_tcu_data3_current_gear_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_current_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_current_gear_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t opel_omega_2001_tcu_data3_selector_position_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_selector_position_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_selector_position_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t opel_omega_2001_tcu_data3_sport_mode_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_sport_mode_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_sport_mode_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_tcu_data3_winter_mode_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_winter_mode_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_winter_mode_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_tcu_data3_auto_neutral_active_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_auto_neutral_active_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_auto_neutral_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t opel_omega_2001_tcu_data3_tcc_state_encode(double value)
{
    return (uint8_t)(value);
}

double opel_omega_2001_tcu_data3_tcc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool opel_omega_2001_tcu_data3_tcc_state_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

int opel_omega_2001_ecu_data4_pack(
    uint8_t *dst_p,
    const struct opel_omega_2001_ecu_data4_t *src_p,
    size_t size)
{
    uint8_t ect;
    uint8_t iat;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ect = (uint8_t)src_p->ect;
    dst_p[1] |= pack_left_shift_u8(ect, 0u, 0xffu);
    iat = (uint8_t)src_p->iat;
    dst_p[5] |= pack_left_shift_u8(iat, 0u, 0xffu);

    return (8);
}

int opel_omega_2001_ecu_data4_unpack(
    struct opel_omega_2001_ecu_data4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ect;
    uint8_t iat;

    if (size < 8u) {
        return (-EINVAL);
    }

    ect = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ect = (int8_t)ect;
    iat = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->iat = (int8_t)iat;

    return (0);
}

int opel_omega_2001_ecu_data4_init(struct opel_omega_2001_ecu_data4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct opel_omega_2001_ecu_data4_t));

    return 0;
}

int8_t opel_omega_2001_ecu_data4_ect_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double opel_omega_2001_ecu_data4_ect_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool opel_omega_2001_ecu_data4_ect_is_in_range(int8_t value)
{
    return (value >= 0);
}

int8_t opel_omega_2001_ecu_data4_iat_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double opel_omega_2001_ecu_data4_iat_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool opel_omega_2001_ecu_data4_iat_is_in_range(int8_t value)
{
    return (value >= 0);
}
